### ISSUE TITLE
using Jekejeke Prolog inside emacs

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [jburse/jekejeke-samples#12]
In emacs, with [ediprolog](https://github.com/triska/ediprologl) or  [prolog.el](https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/prolog.el) it is possible to get a Prolog menu with loading a prolog.pl file .  It would be nice to write a lisp code to load Jekejeke Prolog inside emacs also.

**Comment by jburse** [comment]
We already got a prototype of Emacs mode for Jekejeke Prolog 
Runtime Library. We chose to update prolog.el. Since we put the
amended prolog.el into the samples repository, the issue was

also moved to here. Here is what can be already seen:

![polldnnnkbdlkela](https://user-images.githubusercontent.com/5411487/101267742-7f77ab00-375c-11eb-8f46-61e7a3534131.png)

The modified prolog.el is here:



We will write a little tutorial about how to install Emacs mode for Jekejeke 
Prolog and how to use Emacs mode for Jekejeke Prolog. The tutorial will 
show how to do it independent from some Ubuntu etc.. repository 

support. Shifting it into Ubuntu might be a later goal.

**Comment by joseph-vidal-rosset** [comment]
Le   sam.  12/05/20   déc.   2020  à   03:48:53   ,  "Jekejeke   Prolog"
<notifications@github.com> a envoyé ce message:
> We already got a prototype of Emacs mode for Jekejeke Prolog
> Runtime Library. We chose to update prolog.el. Since we put the
> amended prolog.el into the samples repository, the issue was
>
> also moved to here. Here is what can be already seen:
>
> polldnnn
>
> The modified prolog.el is here:

Hi Jan,

Did you forget to give me the link.  The best for me would be to be able
to use both Jekejeke and SWI.

See you soon,

Jo.

**Comment by joseph-vidal-rosset** [comment]
Sorry,
I replied via emacs and in I did not saw the link in email clientS.
-- 
Joseph

**Comment by jburse** [comment]
The tutorial is there (3x gist comments):
https://gist.github.com/jburse/dfaa1fd638f3397ae83879c124b37f8b#gistcomment-3552298

Yesterday I only tried C-c RET. Today I tried C-c C-l, it did work!
![console_dark_small](https://user-images.githubusercontent.com/5411487/101292295-eb1a5080-380e-11eb-8645-469635432d22.png)

Will now close this ticket. Feel free to open new tickets. There are already 
other tickets concerning Emacs programming mode. Like these here:

- **Integrate our apropos/1 into Emacs prolog.el #13**
   [https://\github.com/jburse/jekejeke-samples/issues/13](https://github.com/jburse/jekejeke-samples/issues/13)
- **Create a non-debugger mode for prolog.el #14**
   [https://\github.com/jburse/jekejeke-samples/issues/14](https://github.com/jburse/jekejeke-samples/issues/14)
- **Emacs prolog.el output coloring glitch #15**
   [https:/\/github.com/jburse/jekejeke-samples/issues/15](https://github.com/jburse/jekejeke-samples/issues/15)

When prolog.el is in good shape we might also hope that
it gets adopted by the maintainer. Please be patient!
